version: '3.8'

services:
  mysql:
    container_name: mysql-sql-test
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password_here
      MYSQL_DATABASE: KHADEMNi
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3308:3308"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-test
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
